#!/bin/bash
set -eu
BREW_PATH="$HOME/dotfiles/Brewfile"

echo ""
echo "===== Install homebrew ====="
echo ""

sleep 0.5
if type brew > /dev/null 2>&1; then
    echo "already installed"
else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi
brew doctor

echo ""
echo "===== Execute 'brew install' ====="
echo ""

sleep 0.5
# virtualbox で躓くことがあるので先にインストールしておく
if type virtualbox > /dev/null 2>&1; then
    echo "Virtualbox is already installed"
else
    brew cask install virtualbox
fi
brew bundle --file=$BREW_PATH

echo ""
echo "Installed homebrew and packages successfully!"
echo ""
