#!/bin/bash
set -eu
BREW_PATH="$HOME/dotfiles/Brewfile"

echo "===== Install homebrew ====="
sleep 0.5
if type brew > /dev/null 2>&1; then
    echo "already installed"
else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "===== Execute 'brew install' ====="
sleep 0.5
# virtualbox で躓くことがあるので先にインストールしておく
if type virtualbox > /dev/null 2>&1; then
    echo "Virtualbox is already installed"
else
    brew cask install virtualbox
fi
brew bundle --file=$BREW_PATH

echo ""
echo "Preinstalled successfully"
echo ""
