#!/bin/bash
set -eu

function has() {
  if [ $# -eq 2 ]; then
    type $1 | grep $2 > /dev/null 2>&1
  else
    type $1 > /dev/null 2>&1
  fi
}

# prezto
echo "===== Install prezto ====="
sleep 0.5
if [ -d ${ZDOTDIR:-$HOME}/.zprezto ]; then
  echo "already installed"
  echo ""
else
  # prezto
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  echo ""
  echo "Prezto is installed successfully"
  echo ""

fi

# powerline fonts
echo "===== Install powerline fonts ====="
sleep 0.5
if find ~/Library/Fonts -name "Ubuntu*" >/dev/null 2>&1; then
  echo "already installed"
  echo ""
else
  ~/dotfiles/fonts/install.sh
  echo ""
  echo "Powerline fonts are installed successfully"
  echo ""
fi

echo "Set up your macOS successfully"
