#!/bin/bash
set -eu

rm -f ~/Downloads/.localized \
  ~/Public/.localized \
  ~/Music/.localized \
  ~/Pictures/.localized \
  ~/Movies/.localized \
  ~/Library/.localized \
  ~/Applications/.localized \
  ~/Desktop/.localized \
  ~/Documents/.localized \
  ~/Downloads/.localized
