.PHONY: ansible mozc nvidia

ansible:
	sudo apt update
	sudo apt install -y python3-pip
	sudo pip3 install ansible

mozc:
	sudo apt install -y ibus-mozc

nvidia:
	sudo add-apt-repository ppa:graphics-drivers/ppa
